[package]
name = "KanyeQuotes"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.2", features = ["json", "blocking"] }
serde = { version = "1.0.219", features = ["derive"] }
