[package]
name = "KanyeInTokio"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = {version = "1.46.0", features = ["full"]}
reqwest = {version = "0.12.22", features = ["json"]}
serde = {version = "1.0.219", features = ["derive"]}
warp = "0.3.7"
